### ISSUE TITLE
Test installation on some larger projects

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#10]
- [x]  ChronoBank - ~~(events have to be resolved)~~
- [x]  Numerai - (uses .solcover.js)
- [x]  Melonport ~~(?) (requires #39)~~
- [ ] Bancorp (requires Node7) 
- [x] Aragon ~~(Cannot figure this out . . . see below).~~
- [x] 0xProject (. . . . .Typescript). 
- [ ] [status-network-token](https://github.com/status-im/status-network-token)

And possibly PR these in? If useful?

**Comment by cgewecke** [comment]
In principle, tool will run on melonport. [Report looks like this](https://sc-forks.github.io/protocol/). Truffle / Solidity-Parser are having a problem with some stub contracts they have, but otherwise everything works.

**Comment by cgewecke** [comment]
Numerai [report looks like this](https://sc-forks.github.io/contract/contracts/index.html)

They had a couple issues worth pursuing. [This line](https://github.com/numerai/contract/blob/master/contracts/NumeraireShared.sol#L64) in their contracts throws a solidity-parser error while instrumenting (but not when compiling with Truffle). Putting the return statement on the same line as the function call resolved it but this may be an SP regression bug. The fork we use is several commits ahead of the published version Truffle uses. 

And some of their minting tests fail non-deterministically under coverage - these fire events. This appears to be a timing related bug (so, basically bad news).

**Comment by cgewecke** [comment]
Bancor @ commit 6e0f2d2 : Lots of tests but not running clear ATM . . . . holding off on this.

**Comment by cgewecke** [comment]
Aragon has a lot of hardcoded gas values - I tried replacing those with much higher sends, and also tried funding accounts with tons of gas. But it still exits with out of gas when deploying the contracts. Just don't know what to do . . . . Possibly revisit.

**Comment by cgewecke** [comment]
0xProject solved by @maurelian.

**Comment by maurelian** [comment]
Changes made for 0x:
* switching to master branch to use [this change](https://github.com/0xProject/contracts/commit/def325ef39747ccd177ea4de3f4c1c976c9c7c0e#diff-f16e8d61c93cd8dbe9a05d4f768d0b78R39)
* modified [this](https://raw.githubusercontent.com/OpenZeppelin/zeppelin-solidity/master/scripts/test.sh) to [this](https://gist.github.com/maurelian/0e1dde4639e67dfb4c5a4e5c78e8c1c2) because account balances were running out
* the migrations had some flow specific to the `development` branch, so [changed](https://github.com/maurelian/0x-contracts/blob/coverage_config/truffle.js) the settings to match the `coverage` network settings required by solidity-coverage. Remember to keep that branch though, or solcover will create one or something. 
* [changed](https://github.com/maurelian/0x-contracts/blob/coverage_config/.solcover.js) the `testCommand` to just `truffle test`

**Comment by cgewecke** [comment]
Closing - no longer really doing this kind of validation.
