### ISSUE TITLE
Strange coverage reported

### ISSUE THREAD

**Issue by aleybovich** [sc-forks/solidity-coverage#193]
I have this function in my contract. As you can see, Solidity coverage reports that it did hit all the branches, but shows `E` in front of one of them, and reports that this branch has not been covered. 

![image](https://user-images.githubusercontent.com/600721/36064689-e58146b4-0e64-11e8-9821-b2dfb6ccf98e.png)

I do have a test case for that last branch, and it works fine - you can see `1x` in the last branch so that code has been executed. Any ideas why it's reporting it as not covered?

**Comment by cgewecke** [comment]
@aleybovich Do you have a test that reaches the final condition but doesn't satisfy it - e.g where `AgentStatus` is not `Active`, `Inactive`, or `None`? If the contract never allows any other values for this property, the last clause could be rewritten as an else (perhaps with a comment indicating the value must be `None`).  If the contract does allow other values, you could just ignore this `E` since the branch is dead regardless. 

It's ok not to have perfect coverage - there are a few cases like this (`assert` is another) where missing a branch is fine because it's either impossible to go down the branch or it's meaningless.
