### ISSUE TITLE
Test cases getting failed

### ISSUE THREAD

**Issue by satyamakgec** [sc-forks/solidity-coverage#225]
I am trying to use the solidity-coverage in my repository but somehow all the test cases are getting failed. While all the test cases are get passed when running the test cases using this cmd `truffle test --network=development`. 

I wonder that maybe the gas issue. I am using the `gas: 0xfffffffffff,` in truffle configuration instead of this my test cases are getting failed. But when I change the gas usage of test cases as `5000000 -> 50000000` then some of the test cases get passed. I don't understand the reason behind this. Is the solidity-coverage testrpc takes more gas consumption in comparison to external ganache-cli?

And do I need to re-locate my `test/helpers/contracts` into `contracts/`? 
Below is the repository link 
https://github.com/PolymathNetwork/polymath-core/tree/coverage

Any help is appreciable

**Comment by cgewecke** [comment]
Hi @satyamakgec. Took a look and there are several issues. You've used Zeppelin's launch scripts (they're great) but changed values in several places. I think the simplest thing to do is just use their scripts as is since they work well.
```javascript
// package.json
"coverage": "./node_modules/.bin/solidity-coverage",  // <-- Current
"coverage": "scripts/coverage.sh", // <-- Zeppelin
```

```shell
#
# solidity-coverage uses its own client called testrpc-sc, not ganache-cli.
#
if [ "$SOLIDITY_COVERAGE" = true ]; then
    node_modules/.bin/testrpc-sc --gasLimit 0xfffffffffff --port "$testrpc_port" "${accounts[@]}" > /dev/null &
  else
    node_modules/.bin/ganache-cli --gasLimit 0xfffffffffff "${accounts[@]}" > /dev/null &
  fi
```

```javascript
module.exports = {
    //testrpcOptions: '--port 8545 -l 5000000',
    norpc: true,
    copyPackages: ['openzeppelin-solidity'],
    skipFiles: ['tokens/STVersionProxy001.sol',
                'tokens/STVersionProxy002.sol',
                'tokens/SecurityTokenV2.sol',
                'interfaces/IModule.sol',
                'interfaces/IModuleFactory.sol',
                'interfaces/IModuleRegistry.sol',
                'interfaces/ISecurityToken.sol',
                'interfaces/ISecurityTokenRegistrar.sol',
                'interfaces/IST20.sol',
                'interfaces/ISTProxy.sol',
                'interfaces/ITickerRegistry.sol',
                'helpers/Util.sol',
                'helpers/TokenBurner.sol',
                'Migrations.sol']
};
```

Finally, re: relocating the helpers. Yes, unfortunately this is necessary since `solidity-coverage` > 4.3 because the coverage tool needs to rewrite the contract ABIs and truffle auto-compiles all contracts in the the `tests` directory, overwriting coverage's work. 

Zeppelin also faced this issue issue and relocated their fixture contracts to a `mocks` folder inside the main `contracts` directory. You will have to move yours and rewrite the import paths etc. You can npm ignore that folder if you are publishing your project.  

With the configuration changes above I was able to get ~40 tests passing.

**Comment by satyamakgec** [comment]
@cgewecke Thanks for writing it. But as you said with the same configuration only ~40 tests are passing remaining 130 are still failing. Because all 170 test cases get passed in the development mode.   What would be the reason for this?

**Comment by satyamakgec** [comment]
run after increasing the gas usage in every test case

**Comment by cgewecke** [comment]
Ah yes! Apologies - I didn't look through your tests. For anyone finding this issue - @satyamakgec had hardcoded gas values in some of his test calls. The coverage tool instruments the code with events and these cost gas to run.  

@satyamakgec Is it ok if I close this? The topic addressed in the FAQ [here](https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-out-of-gas).
