### ISSUE TITLE
The 'copyPackages' option assumes that the '.solcover.js' file resides next to the 'node_modules' folder

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#297]
My relevant directory structure:
- repo:
  - package.json
  - project:
    - .solcover.js
    - truffle-config.js
    - contracts:
      - xxx.sol
    - test:
      - xxx.js

Hence, after `npm install`, the `node_modules` folder is created one folder above the `.solcover.js` file.

As a result, adding `copyPackages: ["openzeppelin-solidity"]` in this file leads to:
```
cp: no such file or directory: node_modules/zeppelin-solidity
```

I also tried `copyPackages: ["../openzeppelin-solidity"]`, which has lead to:
```
cp: no such file or directory: node_modules/../openzeppelin-solidity
```

How do you suggest resolving this?

Thanks

**Comment by cgewecke** [comment]
It assumes that node_modules are in the root folder. That seems correct to me. For example, solidity-coverage works fine in Lerna projects where node_modules packages have been 'hoisted' to an outer directory. Lerna automatically symlinks these to a proxy node_modules folder in the subprojects because it knows that a lot of JS tooling follows this norm. 

I'm going to close this, if people need unconventional file architectures they can do what Lerna manually or use a similar tool to manage it for them.
