### ISSUE TITLE
Add config option 'forceParse'

### ISSUE THREAD

**Issue by maxsam4** [sc-forks/solidity-coverage#301]
Currently, if `deepSkip` is enabled, all the contracts that are skipped are not post processed to remove stuff like `view` modifiers. This leads to compilation failures when the skipped contract has a `view` function and the interface it inherits is not skipped.

Assume there is an interface Imodule and it is implemented by IfirstModule and IsecondModule. Let the interface define a `view` function that both the modules implement. The compilation will fail after instrumenting if we exclude any one of the module as the interface will be processed to convert `view` functions to `non-payable` but the skipped module will still implement it as `view` function.

We can avoid this by setting `deepSkip` to true but then large contracts like OraclizeAPI and other unneeded stuff is processed as well which causes other issues (Timeouts, instrumenting hangs sometimes etc).

I propose that we add a config variable `forceParse` which will be an array like `skipFiles` and entries in it will be force parsed even if deepSkip is set to true.

Alternatively, we can make `deepSkip` an array and skip only the files in that array.
I prefer the first option as it won't require unaffected users to change their config.

Update: I have created a PR to fix this.

**Comment by cgewecke** [comment]
@maxsam4 Thanks so much for your PR and for your excellent description of the issue here. 
In `0.6.0` the preprocessing algo has been improved - the older oraclize contract which used to take 30 minutes to instrument now takes ~1 sec.  

Additionally, am going to try some changes this monty that should remove the necessity of preprocessing for view and pure altogether - I think that's the best way forward in the long run. 

Leaving this open for further consideration - it's a nice solution.

**Comment by cgewecke** [comment]
`0.7.0` has resolved all this by using a completely different architecture.
