### ISSUE TITLE
Test of externally compiled contract fails when generating coverage

### ISSUE THREAD

**Issue by WyseNynja** [sc-forks/solidity-coverage#314]
My contract is written in solidity 0.5. It depends on a contract written by someone else in solidity 0.4. I've managed to get migrations and tests working for the external contract by using an external compile step (https://github.com/trufflesuite/truffle/issues/1607#issuecomment-452159899).

Most of my tests still work, but one that was calling getBalance against gastoken now errors:
```
  it("... should have some gas token to burn.", async () => {
    const gasTokenInstance = await GasToken2.deployed();

    await gasTokenInstance.mint(100, { from: accounts[3] });

    let balance = await gasTokenInstance.balanceOf(accounts[3]);
    assert.equal(balance, 100);
  });
```
```
  1) Contract: GasToken2
       ... should have some gas token to burn.:
     AssertionError: expected { Object (tx, receipt, ...) } to equal 100
      at Context.it (test/gastoken.js:13:12)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

This test passes `truffle test`.  I'm sure this is because the contract is compiled with solc-0.4.25 and not with truffle's normal flow. One major difference is the json generated by the external compile step doesn't have as many keys as the normal files: https://gist.github.com/WyseNynja/e54064191465abc3c662b3b2df1e4280

What do I need to do to get coverage not breaking tests for my external contracts? Is it simply keys missing from my JSON, or is there something bigger I have to do? I'm guessing it is something bigger.

I'm fine if I don't actually get coverage reports for the external contracts since they have test suites of their own and I can just test my interfaces, but my tests failing is a problem.

**Comment by WyseNynja** [comment]
After more investigation, I think this failure is actually being caused by a combination of eth-gas-reporter and solidity-coverage. Once I disabled eth-gas-reporter, this test passed under solidity-coverage

**Comment by WyseNynja** [comment]
Actually. I can't get the test to fail at all now. It must have been something else.

**Comment by WyseNynja** [comment]
I think I'm tired. I c

**Comment by WyseNynja** [comment]
For a few minutes I thought eth-gas-reporter was related to the error, but I removed it and still got this same failure. I'm thinking the error is coming from the compiler of gastoken not matching the rest of the project.

**Comment by angus-hamill** [comment]
@WyseNynja what's happening here is that truffle is calling web3's `send()` method rather than `call()` and hence returning a transaction receipt rather than the actual value returned by the method.

The reason this is happening is because solidity-coverage is adding a coverage event to the method as a part of it's instrumenting step (hence making the method non-view). Truffle calls the different web3 methods based on the value `constant` for each method in `build/GasToken2.json`.
solidity-coverage gets around this usually because the contracts are instrumented AFTER `truffle compile` hence the JSON will have `"constant": true` even though the method is technically no longer constant. It's hacky but it works.

This leaves you with 2 options:
1. Get solidity-coverage to run the contract instrumentation after `truffle compile`
2. Somehow manually change the `constant` value for `balanceOf` in `GasToken2.json` before the tests run

Hopefully this helps (I realise that this was a while ago so you may have already figured it out)

**Comment by WyseNynja** [comment]
Option 3 sounds like it should cover all the cases I can think of. Thanks.
