### ISSUE TITLE
Compilation hangs

### ISSUE THREAD

**Issue by justinkchen** [sc-forks/solidity-coverage#325]
For some reason, the second time it compiles, after instrumentation, it is hanging and never completing. There is no error message or anything, it just never completes. We are using a library linked list and trying to initialize it in the constructor of one of the contracts but it fails to finish compiling in coverage but it works with normal compilation (the first time through).  Other methods in the library work fine and even if we make the method do absolutely nothing, for some reason it just never completes.

**Comment by cgewecke** [comment]
@justinkchen If you have a chance could you try with `0.6.0`? Or point me in the direction of the repo?

**Comment by cgewecke** [comment]
Closing for housekeeping, please ping if anyone continues to see this in the latest versions.

There can be a long wait between the second compilation and the start of tests running. It's actually `JSON.parse`  running within Truffle and is also the source of some OOM faults that are documented in the README.

**Comment by JasoonS** [comment]
I have this issues with this code base: https://github.com/wild-cards/contracts

I will try switch to 0.6 *

**Comment by cgewecke** [comment]
@JasoonS Hi, in your case the hang is caused by an interaction between eth-gas-reporter and solidity-coverage. The gas-reporter makes synchronous http calls and requires that the ethereum node run in a separate process (or else the execution locks). Solidity-coverage@beta is the opposite - it requires the ethereum node be in *the same* process the tests so it can monitor the node's VM. 

You can set the mocha reporter solidity-coverage 0.7.0-beta.2 uses by adding a .solcover.js file with:

```javascript
module.exports = {
  mocha: { reporter: 'spec' }
}
```

I was able to run your tests with 
```
npx truffle run coverage --network test
```

There were 3 failures, all related to hardcoded expectations about how much execution requires. The coverage tool distorts gas usage a little. There's more on these topics in the docs here:
+ [gas distortion](https://github.com/sc-forks/solidity-coverage/blob/beta/docs/faq.md#notes-on-gas-distortion)
+ [skipping tests](https://github.com/sc-forks/solidity-coverage/blob/beta/docs/advanced.md#skipping-tests)

**Comment by JasoonS** [comment]
@cgewecke Thank you so much! You are a rock star!

**Comment by cgewecke** [comment]
@JasoonS Thanks for trying the beta and reporting this bug! Super helpful.
