### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by fabianorodrigo** [sc-forks/solidity-coverage#355]
In spite of the usage notes say "For pragma solidity >=0.4.22 <0.6.0" and I have in my truffle-config.js the compiler set to '0.4.24', solidity-coverage generate a 'truffle-config.js' in the 'coverageEnv' folder that doesn't have the original compiler version configuration. Consequently I've got a compilation fail: Error: Truffle is currently using solc 0.5.8, but one or more of your contracts specify "pragma solidity ^0.4.23".

**Comment by cgewecke** [comment]
@fabianorodrigo If you add a coverage network to your truffle-config.js following [the README](https://github.com/sc-forks/solidity-coverage#network-configuration) instructions then solidity-coverage will use your truffle config file (instead of it's own) and this problem should go away.

**Comment by cgewecke** [comment]
@fabianorodrigo Did you get it to work? Is this issue closable?

**Comment by fabianorodrigo** [comment]
> @fabianorodrigo Did you get it to work? Is this issue closable?

Actually It worked in the way that I have no longer problems related to the compiler version. But now I got another compilation error:  TypeError: Overriding function changes state mutability from "view" to "nonpayable".

The project that I'm trying to run solidity-cover is this: https://github.com/decentraland/marketplace-contracts

**Comment by fabianorodrigo** [comment]
For the project https://github.com/harmvandendorpel/left-gallery-token it had no compilation errors and executed successfully the tests (5 passing) but in the end of execution I got: 

"Cleaning up...
Shutting down testrpc-sc (pid 9993)
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage..."

This is my truffle-config.js

module.exports = {
networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*"
    },
    coverage: {
      host: "localhost",
      network_id: "*",
      port: 8555,         // <-- If you change this, also set the port option in .solcover.js.
      gas: 0xfffffffffff, // <-- Use this high gas value
      gasPrice: 0x01      // <-- Use this low gas price
    }
},
  compilers: {
    solc: {
      version: "0.4.24",
    }
  }
}

**Comment by cgewecke** [comment]
The decentraland contracts have native solidity tests in their `tests` folder - at the moment solidity-coverage cannot manage those. This is a known limitation documented in the README (see [Usage Notes](https://github.com/sc-forks/solidity-coverage#usage-notes)). Should be fixed in `0.7.0.`

With the `left-gallery-token`, there are both truffle.js and truffle-config.js files in the root folder which is confusing the tool (this is a bug). I removed truffle.js, used your config and got:
![Screen Shot 2019-07-24 at 6 47 14 PM](https://user-images.githubusercontent.com/7332026/61839789-c274ff00-ae43-11e9-9697-45beb420b802.png)

I'm going to open a separate issue about multiple config files and close this one
