### ISSUE TITLE
Bump solidity-parser to 0.9.1

### ISSUE THREAD

**Issue by junderw** [sc-forks/solidity-coverage#575]
Currently using separated `hex'ffff' hex'ffff'` hex literals causes solidity-coverage to break.

**Comment by cgewecke** [comment]
Ok thanks @junderw.

**Comment by cgewecke** [comment]
@junderw 

The parser has been receiving quite frequent updates that don't automatically propagate, e.g from 0.7.x to 0.8.x. because of [the way npm interprets 0-series caret ranges][1] 

If you need to use improvements there immediately and you're open to installing with `yarn`, you might be interested in yarn's [selective-version-resolutions][2] feature which lets you coerce sub-dependencies of a module to whatever version you prefer.  

[1]: https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004
[2]: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by junderw** [comment]
perhaps 0.9.x would work?

**Comment by junderw** [comment]
looks like using ^0.9.x will allow anything <0.10.0

would using that for a dep be ok for this library.

**Comment by cgewecke** [comment]
Yes it would work - I just mean this project doesn't publish at the same cadence and we'd need to re-publish to update that dependency. I am waiting for bugs to be reported about the Hardhat plugin and probably will not cut another release until those are reported / resolved, maybe next week.   

I think the linter may be much more sensitive to what constitutes a breaking change in the parser than this tool is (hence the frequency of what are de-facto major version releases there,  e.g. ~1 per month).

**Comment by cgewecke** [comment]
Update:  `0.9.x` is using a new [antlr4 runtime which requires Node >= 14][1]. (LTS as of late October)

To not break people whose CI still running on 12, this dep update will need to go in the next minor version bump (`0.8.x`) which is scheduled for end of December.

[1]: https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md#is-nodejs-supported

**Comment by cgewecke** [comment]
Sorry for the delay fixing this...`0.7.14` includes the latest solidity-parser/parser: `v0.11.0`

**Comment by junderw** [comment]
Thanks a lot!
