### ISSUE TITLE
0% coverage reported when stub contract outside contracts folder

### ISSUE THREAD

**Issue by elenadimitrova** [sc-forks/solidity-coverage#620]
When the `ArgentModuleTest` contract is in the `/contracts-test` folder instead of `/contracts` [coverage reports 0%](https://2091-166830546-gh.circle-artifacts.com/0/coverage-artifacts/modules/index.html) on the `ArgentModule` (which is the base of `ArgentModuleTest`). When we move `ArgentModuleTest` to the contracts folder though this resumes reporting correctly.

This is demonstrated by the last two commits [here](https://github.com/argentlabs/argent-contracts/pull/193/commits)  where one fails and the other passes coverage depending only on the test contract location.

**Comment by cgewecke** [comment]
@elenadimitrova  In argentcontracts/.solcover.js, it looks like that folder's being skipped:
```
module.exports = {
  client: require('ganache-cli'),
  skipFiles: [
    "../contracts-test",
    "../contracts-legacy",
    "../lib"
  ],
  providerOptions: {
    port: 8555,
    _chainId: 1895,
    network_id: 1597649375983,
    account_keys_path: "./ganache-accounts.json",
    default_balance_ether: 10000
  }
};
```

Does unskipping fix?

**Comment by cgewecke** [comment]
Oh wait, I misread your description...`ArgentModule` is the problem.

**Comment by cgewecke** [comment]
@elenadimitrova There isn't a perfect solution here unfortunately. 

`ArgentModuleTest` imports `ArgentModule` as if it were an external dependency but we can't safely instrument those while preserving the import path of the coverage target. 
```solidity
import "../contracts/modules/ArgentModules";
```
For that to work we'd have to also instrument `contracts/` directly instead of using a temporary folder to stage the mangled files.

Most people manage this limitation by having a `mocks` folder in `contracts`. An example is at [zeppelin-contracts][1]. That folder is added to `skipFiles` so it doesn't end up in the report. And npmignore'd if you're publishing as a package. 

Is that pattern workable? 

[1]: https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/mocks

**Comment by elenadimitrova** [comment]
We'll make it work, thanks @cgewecke
