### ISSUE TITLE
Stack too deep!!!!

### ISSUE THREAD

**Issue by odd-amphora** [sc-forks/solidity-coverage#675]
Hi! We would love to use solidity-coverage over at [juicebox.money](https://juicebox.money) as we are writing a new version of the protocol. I have tried using the `configureYulOptimizer` flag, but it seems to have no effect... our (new) contracts repo can be found here: https://github.com/jbx-protocol/juice-contracts-v2. If there's anything you can do to help us out, it would be greatly appreciated!

**Comment by odd-amphora** [comment]
The error specifically in question is the following:

```
CompilerError: Stack too deep, try removing local variables.
   --> contracts/JBETHPaymentTerminalStore.sol:285:10:
    |
285 |         (_preferClaimedTokensAndBeneficiary & 1) == 0,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error in plugin solidity-coverage: HardhatError: HH600: Compilation failed
```

**Comment by cgewecke** [comment]
Hi @odd-amphora. 

Could you try installing solidity-coverage@eip165 (which has a fix that may reduce the stack pressure)?

Another possibility solution is in #636 (which predates the yul option) where someone suggests using the fork of solidity-coverage below (it implements the same logic the option is supposed to toggle).

Could you see if installing their version resolves things for you? 

https://github.com/Float-Capital/solidity-coverage

If the fork works (or anything really), could you report results back here?

Thanks and apologies....

**Comment by odd-amphora** [comment]
@cgewecke unfortunately neither of those proposed solutions solve the issue :| Any other ideas?

**Comment by cgewecke** [comment]
Ok will take a look at your repo and try to reproduce ...

**Comment by odd-amphora** [comment]
Thank you!

**Comment by odd-amphora** [comment]
Any luck @cgewecke?

**Comment by cgewecke** [comment]
Yes.

If you go into solidity-coverage in your local `node_modules` and modify the compiler configuration in the [plugins/hardhat.plugins.js][1] file to the settings below, compilation works and coverage seems to be generated. (Make sure configureYulOptimizer option is set to true)

[1]: https://github.com/sc-forks/solidity-coverage/blob/cdab28ca07534c71d9383f0a289aa28ec40a4e42/plugins/hardhat.plugin.js#L61

```js
// Override optimizer settings for all compilers
settings.optimizer.enabled = false;

// This is fixes a stack too deep bug in ABIEncoderV2
// Experimental because not sure this works as expected across versions....
if (configureYulOptimizer) {
  settings.optimizer.details = {
    peephole: false,
    inliner: false,
    jumpdestRemover: false,
    orderLiterals: true,  // <-- TRUE! Stack too deep when false
    deduplicate: false,
    cse: false,
    constantOptimizer: false,
    yul: false
  }
}
```

I had another weird error from hardhat because a mnemonic wasn't set on the network ... to get around that I created an entry for `hardhat` in the networks config and specified one for the accounts object (like your other networks) and ran coverage like:

```
npx hardhat coverage --network hardhat
```

This is what I got...
![Screen Shot 2021-11-23 at 2 48 07 PM](https://user-images.githubusercontent.com/7332026/143141211-c2b297ee-928d-4a89-b17f-1079964c6025.png)

In terms of fixing this problem here.... tbh I don't know whether compiler optimization is changing a lot from release to release and whether there is a "one-size-fits-all" solution for stack too deep issues.

One way forward might be to let people override the compiler settings instead of trying to over-manage them and provide some recipes in the README for configurations that have worked in the past. 

In the short term I recommend forking the project and modifying the internals so that it works for you. This is just a js repo and you can yarn install it from git without building, etc.

**Comment by odd-amphora** [comment]
I see. I definitely suggest trying to support this in the core library as I think many protocols with more complicated contracts could benefit – maybe I will consider making a PR once it's working. I tried exactly as you said, but the coverage is not matching.... JBOperatorStore is showing no coverage; it and JBPrices should now have coverage. Here is the work in progress changes: https://github.com/jbx-protocol/juice-contracts-v2/pull/20/files. Any help to pull this across the finish line would be greatly appreciated!

**Comment by odd-amphora** [comment]
Okay... I ended up getting it to work with preempting the hardhat binary with esm. That's probably not solvable on your end because it seems like they are delaying esm support, but I'd still love to see, or help contribute to, the compiler optimization stuff.

**Comment by cgewecke** [comment]
Oh great ok. 

Yeah I removed the esm stuff too, wasn't sure if that was erroring because of my node version or not.

From the issues in this repo it's really unclear if there are multiple paths to a stack too deep error or if Solidity's optimizer implementation is consistent across versions. 

The whole thing seems weird ... like ... you need to turn the optimizer off *and* set the  correct combination of optimization settings to get the contracts to compile? Some settings work for some versions and others for others? 

I know this is a common problem esp. w/ solc 0.8.x and big codebases.... definitely needs to be addressed. 

Thanks!
