### ISSUE TITLE
Coverage not working with hardhat `forking` params

### ISSUE THREAD

**Issue by riordant** [sc-forks/solidity-coverage#685]
Hi,
coverage does not appear to be working when `forking` parameters are set in the hardhat config. Coverage is always zero  for all files apart from the interfaces in my project. Should it be working with this configuration? thanks

**Comment by cgewecke** [comment]
Yes, it should be working. There have been issues in the past with forking when `hardhat_reset` is called somewhere in the test suite but those should be resolved in the latest version (0.7.18)

We have a working integration test for forked provider tests in the repository here:

https://github.com/sc-forks/solidity-coverage/tree/master/test/integration/projects/hardhat-reset

If you've updated to the latest version and you're still seeing an empty report, checking for differences between that test project and yours might help isolate what the issue is. 

(Would also recommend running `npx harhdat clean` before running coverage just to make sure you aren't running into cacheing issues)

**Comment by riordant** [comment]
Got it working, issue was I was  using older version. Thank you very much. Closing
