### ISSUE TITLE
Compilation failure when whitespace between `require` and terminating semi-colon

### ISSUE THREAD

**Issue by AntonGulak** [sc-forks/solidity-coverage#882]
Hi again :)

Contracts compiled with Solidity 0.4.21 are failing to compile when they include **require(bool)** statements, resulting in a 
`ParserError: Expected token Semicolon got 'Identifier' error. Specifically,  require(false) c_3a887c65(0x55bf89d8a3187e04); /* requirePost */ HardhatError: HH600: Compilation failed.`

Compilation succeeds without coverage

Thank you for the quick response

**Comment by cgewecke** [comment]
@AntonGulak This seems to be caused by the presence of extra space between the `require` and the terminating `;`

A work-around is to change the code as below
```diff
- require(false) ;
+ require(false);
```

Unfortunately it's a little tricky to fix this - ideally the parser we use would include the semi-colon in its reporting of the expression range but it doesn't...

**Comment by cgewecke** [comment]
This has been patch via #884 and published in v0.8.12.

(Thanks again for finding all these bugs!!)
